apiVersion: serving.knative.dev/v1
kind: Service
metadata:
     name: helloworld-go
     namespace: abcsl
spec:
     template:
       spec:
         containers:
           - image: quay.io/rhn_support_abaral1/go-web-app:latest
      
